'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PaymentRequest
    
    '''<summary>
    '''lblPaymentId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaymentId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTshirt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTshirt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCardHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCardHolder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCardNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCardNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblExpiryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpiryDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCardSecurityCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCardSecurityCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RedirectForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RedirectForm As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''Panel_Debug control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Debug As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label_Debug control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Debug As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_DigitalOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_DigitalOrder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Panel_StackTrace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_StackTrace As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label_StackTrace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_StackTrace As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Message As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Amount As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''BankId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankId As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''CardNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CardNumber As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''CardHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CardHolder As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''CardSecurityCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CardSecurityCode As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''Currency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Currency As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''ExpiryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpiryDate As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''MCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MCC As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''PassCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PassCode As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''ReturnURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReturnURL As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''TxnRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxnRefNo As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''TxnType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxnType As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''MerchantId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MerchantId As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''TerminalId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TerminalId As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''Version control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Version As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
