'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DashBoard

    '''<summary>
    '''AdminSideMenuControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdminSideMenuControl As Global.EktaTrust.AdminSideMenuControl

    '''<summary>
    '''lblTotalVisitor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalVisitor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalUsers As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalDonations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalDonations As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ChartScriptLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartScriptLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''regUserLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regUserLiteral As Global.System.Web.UI.WebControls.Literal
End Class
