'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PaymentResponse
    
    '''<summary>
    '''Panel_Debug control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Debug As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label_Debug control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Debug As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_DigitalOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_DigitalOrder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Title As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_MerchTxnRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_MerchTxnRef As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_OrderInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_OrderInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_MerchantID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_MerchantID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_Amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Amount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_TerminalId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_TerminalId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_TxnResponseCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_TxnResponseCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Message As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Panel_Receipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Receipt As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label_RetRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_RetRefNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_BatchNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_BatchNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_AuthorizeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_AuthorizeID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_CardType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_CardType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_CardNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_CardNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_CAVV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_CAVV As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_UCAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_UCAP As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_AuthStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_AuthStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_ENROLLED control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_ENROLLED As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_HashValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_HashValidation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Panel_StackTrace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_StackTrace As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label_StackTrace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_StackTrace As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label_AgainLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_AgainLink As Global.System.Web.UI.WebControls.Label
End Class
