'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PaymentProcess
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''CardHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CardHolder As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''reqCardHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqCardHolder As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''CardSecurityCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CardSecurityCode As Global.System.Web.UI.HtmlControls.HtmlInputPassword
    
    '''<summary>
    '''reqCardSecurityCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqCardSecurityCode As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''CardNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CardNumber As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''reqCardNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqCardNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlExpiryMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExpiryMonth As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''ddlExpiryYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExpiryYear As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''inprocess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inprocess As Global.System.Web.UI.WebControls.Button
End Class
